name: flutter_design_pattern
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  equatable: ^2.0.3
  flexible_tree_view: ^0.0.2
  fluro: ^2.0.3
  font_awesome_flutter: ^10.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_screenutil: ^5.3.1
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.1
  graphview: ^1.1.1
  intl: ^0.17.0
  markdown_widget: ^1.2.8
  flutter_breadcrumb: ^1.0.1
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
